### PR TITLE
Relaxes Ruby dependency to work with Ruby 3

### PR DESCRIPTION
**Pull request by walski**
Tested with `3.0.0-preview1` and all tests are green:

```
Loaded suite /Users/walski/.rubies/ruby-3.0.0-preview1/lib/ruby/gems/3.0.0/gems/rake-13.0.1/lib/rake/rake_test_loader
Started
................................................................................................................................................................................
................................................................................................................................................................................
................................................................................................................................................................................
................................................................................................................................................................................
................................................................................................................................................................................
.......................
Finished in 4.225482 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
903 tests, 2962 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
213.70 tests/s, 700.99 assertions/s
Coverage report generated for Unit Tests to /Users/walski/projects/os/caxlsx/coverage. 5160 / 5161 LOC (99.98%) covered.
```

### CODE REVIEW

**Comment by StoneGod** [comment]
Hi, Ruby 3.0.0 released

**Comment by Laykou** [comment]
@noniq  @straydogstudio  Do you think we could have this merged in order to support the latest Ruby version? Thank you

**Comment by simi** [comment]
@walski would it be possible to target 3.0.0 on Travis? Current preview version is failing.

**Comment by Laykou** [comment]
RVM is probably not configured. https://travis-ci.com/github/caxlsx/caxlsx/jobs/454304024 
Is it something anyone can fix or only the repo admin?

image

**Comment by straydogstudio** [comment]
That notice is an rvm error. Has it been tried without "-preview1"? Precompiled rubies show up as "ruby-3.0.0", and Ubuntu Trusty (14.04) lists it available as precompiled. See:

https://rubies.travis-ci.org/

**Comment by walski** [comment]
This was quite a ride to convince Travis to play ball here. What seems to have made it possible in the end:

### 1. Switch to Ubuntu 18.05 (bionic)

Solved RVM signing/verification issues, that I could not overcome by just importing GPG keys, which seemed to have worked on Travis at some point.


### 2.  Remove Rubinius from build matrix

For details see https://github.com/caxlsx/caxlsx/pull/72/commits/5273b5724b577d9090801b3e9a1dc6cbd577d38b

---

And 2 hours later it's green on Travis ;)

**Comment by Laykou** [comment]
The weird thing is that I use only `gem 'caxlsx_rails'` in my Gemfile and I was able tu successfully bundle install on ruby 3.0.0 :O

**Comment by straydogstudio** [comment]
Thanks for the work @walski it is probably time we moved to a newer Ubuntu version anyway. 

As long as Travis passes, anyone have issues with bumping our Travis build to bionic?

**Comment by straydogstudio** [comment]
@Laykou Yeah the gem requirements for building in development/testing are more extensive than runtime. And just including `caxlsx_rails` is a bit more lax. I've never taken the time to figure out why, but as long as things work I've never tried to go further.

**Comment by walski** [comment]
Any chance to get this moving forward and released on rubygems.org? Can I be of any further help?

**Comment by straydogstudio** [comment]
Merged. At least you can use the git repo.

**Comment by simi** [comment]
@straydogstudio anything blocking release? I thnk I have rg.org access to this gem to push if needed.

**Comment by straydogstudio** [comment]
Did we have another pull request that was waiting in the wings? I thought there was something that we wanted to put in 3.0.4 before bumping to 3.1.0. We can always do a 3.0.5.

**Comment by straydogstudio** [comment]
It was #70. I've got a note out to @noniq who made suggested changes. I'll wait a short bit and release this as 3.0.4 tonight.

**Comment by straydogstudio** [comment]
Released in 3.0.4

**Pull request merged**
