### PR TITLE
Freeze strings :snowflake: :snowflake: :snowflake:

### PR DESCRIPTION
**Pull request by gdimitris**
~ 24% more better performance on modern rubies

### CODE REVIEW

**Comment by gdimitris** [comment]
Following up on https://github.com/caxlsx/caxlsx/pull/12#issuecomment-547207847 from @noniq I created this PR that contains only the changes with the frozen_string_literal pragma.

**Comment by noniq** [comment]
@gdimitris Thanks! Please check the CI results, there’s obviously at least one test that’s now failing.

**Comment by gdimitris** [comment]
Thanks @noniq I will check the results tomorrow!

**Comment by gdimitris** [comment]
Fyi, I haven't forgot about this. It has been a bit hectic lately. I'll try to make time for this so we can merge it

**Comment by westonganger** [comment]
@gdimitris any chance to revisit this or should I pick this one up where you left off? I wanna get this improvement merged.

**Comment by gdimitris** [comment]
Unfortunately, it is really busy for me until end of Feb. If this is urgent for you feel free to pick it up! Many thanks!

**Comment by westonganger** [comment]
I tried giving this a shot but honestly I dont think its likely to happen. The code I see in axlsx re-uses strings to their maximum, sometimes it doesnt even make sense what string its appending to.

The only way I could see this being achieved is file by file individually added the frozen string literal comment and checking if it is compatible off the bat.

That being said I don't think enabling this flag in any file is a good idea for this library.

**Comment by noniq** [comment]
@westonganger Thanks for looking into this! You’re probably right – if I remember correctly there have been numerous efforts of improving performance in the past, and unfortunately some seem to have led to a state where further optimizations like freezing all strings are very hard to implement.

In general it would be interesting to do a profound performance analysis (especially focussed on memory consumption when generating huge xlsx files): Maybe we could identify a handful of “hot paths” and try to focus optimization efforts on these. But I’m afraid this would be quite a lot of work.

**Pull request closed without merging**
