### PR TITLE
Chore/remove encoding magic comments

### PR DESCRIPTION
**Pull request by tagliala**
### Description
- Remove old comments
- Strip some CR end of lines in a ruby file
- Add a default editorconfig to prevent trailing whitespaces and CRLF end of lines

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [ ] I added an entry to the [changelog](../blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by kiskoza** [comment]
I would set up a rubocop if we're trying to keep the code clean - we don't need to use all rules, but would be nice to use it in the CI as well, so we won't bring back trailing white spaces or unnecessary empty lines, etc.

**Comment by tagliala** [comment]
> I would set up a rubocop if we're trying to keep the code clean - we don't need to use all rules, but would be nice to use it in the CI as well, so we won't bring back trailing white spaces or unnecessary empty lines, etc.

If Rubocop is ok for you, I'm a fan of RuboCop and I would be happy to introduce just a few rules with simple automatic correction and also provide a separate GitHub action to lint (example: https://github.com/enriclluelles/route_translator/actions/runs/4387159185)

If you also need temporary help, feel free to add me to maintainers, mostly because of #189 (without that fix I should fork or monkey patch caxlsx)

**Comment by tagliala** [comment]
@kiskoza you can see work in progress here:
- https://github.com/tagliala/caxlsx/actions/runs/4620620569
- https://github.com/tagliala/caxlsx/pull/1

**Comment by tagliala** [comment]
Superseded by #191

**Pull request closed without merging**
