### PR TITLE
Cleanup README

### PR DESCRIPTION
**Pull request by westonganger**
This PR cleans up the readme

### CODE REVIEW

**Comment by noniq** [comment]
Hm, do we really want to have the detailled information about related gems (together with some other some) removed from the first section? What’s your rationale for this change?

**Comment by westonganger** [comment]
For the information regarding additional gems, I did not like how it was the first thing in the readme instead of explaining this gem first. We could add another section for `Plugins / Integrations` with fresh information regarding these.

The details section always bothered me, highlighting outdated things like 
- Release Date from 2013
- IRC (outdated)
- Google groups (outdated, we should just use github/stackoverflow  instead)
- Copyright years that are not kept current
- Pointing at JRuby and Rubinius (we dont even test against these)

**Comment by noniq** [comment]
Makes sense. Let’s add a section with information about the other gems, and remove the outdated details. We should also add a link to `docs/style_reference.md` (and to `docs/header_and_footer_codes.md` if there is none yet).

**Comment by westonganger** [comment]
Alright this should be complete now

**Comment by noniq** [comment]
Merged, thanks a lot!

**Pull request merged**
