### PR TITLE
Add caxlsx.rb to make auto require work

### PR DESCRIPTION
**Pull request by kiskoza**
https://guides.rubygems.org/make-your-own-gem/
The convention is to have one Ruby file with the same name as your gem, since that gets loaded when require is run.

### CODE REVIEW

**Comment by straydogstudio** [comment]
@kiskoza In what context did you find this? Was it Rails, or something else?

**Comment by kiskoza** [comment]
@straydogstudio I've got a rails project, where I used to have axlsx. After migrating to xaxlsx, I had to add a require line to make it work again. Then I started to look into why it isn't working with this new gem, and here we are.

I tried out these changes, and it solved the issue, so I decided to make a PR about it. (Also I have a todo comment on that line saying this probably won't be required on the next version)

**Comment by straydogstudio** [comment]
@kiskoza That's what I expected but i wanted to make sure. Thanks. I'll release a 3.0.1 fix shortly.

**Comment by straydogstudio** [comment]
3.0.1 released with this pull request.

**Pull request merged**
