### PR TITLE
Allow border style to accept an Array

### PR DESCRIPTION
**Pull request by westonganger**
Solves #111

### CODE REVIEW

**Comment by kiskoza** [comment]
I made a quick look at this PR and we shouldn't bring back `examples/example.rb` - might be an accidental file addition?

**Comment by westonganger** [comment]
@kiskoza yes that legacy file was not supposed to be there. I have updated the PR.

**Review by simi — APPROVED** [review]

**Comment by kiskoza** [comment]
The examples file is there again, I think something went wrong with the force pushes

**Comment by westonganger** [comment]
Sorry about that, had a nasty git session last week. I've now fixed this again.

**Comment by straydogstudio** [comment]
@westonganger Can you give an overview of the algorithm changes you have made?

**Comment by westonganger** [comment]
@straydogstudio reading the original issue report explains it quite well I think, https://github.com/caxlsx/caxlsx/issues/111#issue-1050690482

**Comment by straydogstudio** [comment]
@kiskoza @simi @noniq I'm inclined to merge this, even though it adds a bit of complication that may have long term consequences. The tests pass, and it has backwards compatibility. Any thoughts?

**Pull request merged**
