### PR TITLE
improvement: cell_range optimization

### PR DESCRIPTION
**Pull request by olegykz**
Hey guys,
I've found out that gem is quite slow when it comes to the big chart generation (big in the context of the amount of series and data points). After some research, I've come to `cell_range` method - it's sorting cells array to detect minimum and maximum positions. So I asked myself - why we're sorting the data while we need only min and max? I've replaced sorting with `Enumerator.minmax` invocation and it gave me 3x times speed-up in production (from ~45 sec to ~18 sec, for 60K data points & 50+ series, scatter chart)

Here is the synthetic benchmark code:
```ruby
random_row = -> { Array.new(5_000) { rand(100) } }

Benchmark.bmbm do |x|
  x.report('scatter_chart') do
    p = Axlsx::Package.new
    wb = p.workbook
    sheet = wb.add_worksheet
    chart = sheet.add_chart(Axlsx::ScatterChart)
    10.times do
      x_data = sheet.add_row(random_row.call)
      y_data = sheet.add_row(random_row.call)

      chart.add_series(
        yData: sheet["#{y_data.cells.first.reference}:#{y_data.cells.last.reference}"],
        xData: sheet["#{x_data.cells.first.reference}:#{x_data.cells.last.reference}"]
      )
    end

    p.serialize('big_scatter.xlsx')
  end
end
```

And results (MacBook pro'19):
```
# olegykz/speed-up
# Rehearsal -------------------------------------------------
# scatter_chart   6.576812   0.102391   6.679203 (  6.692438)
# ---------------------------------------- total: 6.679203sec
#                     user     system      total        real
# scatter_chart   6.115650   0.066574   6.182224 (  6.191830)

# 3.04
# Rehearsal -------------------------------------------------
# scatter_chart  19.051392   0.149456  19.200848 ( 19.296374)
# --------------------------------------- total: 19.200848sec
#                     user     system      total        real
# scatter_chart  19.877533   0.074367  19.951900 ( 19.987771)

```

P.S. TBH, I'm not sure if it's needed to detect min/max cell at all as for me it looks like the usual use-case for charts is to send something like `xData: sheet['A1:A777']` which already gives an ordered array of cells

### CODE REVIEW

**Comment by kiskoza** [comment]
Nice catch! The code change looks good to me.

You can define a cell range by providing the first and last cell instead of a string literal or giving an array of cells, so these should be equivalent:

```ruby
# 1) Your code with string references
chart.add_series(
    yData: sheet["#{y_data.cells.first.reference}:#{y_data.cells.last.reference}"],
    xData: sheet["#{x_data.cells.first.reference}:#{x_data.cells.last.reference}"]
)

# 2) The same using the cells itself
chart.add_series(
    yData: [y_data.cells.first, y_data.cells.last],
    xData: [x_data.cells.first, x_data.cells.last]
)

# 3) Add all of the cells as the range
chart.add_series(
    yData: y_data.cells,
    xData: x_data.cells
)

```

In my opinion 1) is more readable when you have a fixed set of cells and you can write for example `A5:D7`. 2) is misleading in every way, I don't recommend using it, however 3) looks a lot nicer than 1). Unfortunatelly, you can't say that 3) is sorted every time (could have a more complex method to get the list of the cells), so we should leave the minmax for now.

**Comment by olegykz** [comment]
@kiskoza tbh I haven't paid a lot of attention to the test code - the only criteria for me was the readability

**Comment by kiskoza** [comment]
@olegykz Your test code is totally fine. I just wanted to show some use cases where we might need the minmax to be there :)

**Comment by olegykz** [comment]
@kiskoza oh, now I got your point. You're right that your options are equivalent - but only in terms of what you see in the result table. Here is another test:

```ruby
random_row = -> { Array.new(10_000) { rand(100) } }

Benchmark.bmbm do |x|
  x.report('adding series by full range') do
    p = Axlsx::Package.new
    wb = p.workbook
    sheet = wb.add_worksheet
    chart = sheet.add_chart(Axlsx::ScatterChart)

    10.times do
      x_data = sheet.add_row(random_row.call)
      y_data = sheet.add_row(random_row.call)

      chart.add_series(
        yData: sheet["#{y_data.cells.first.reference}:#{y_data.cells.last.reference}"],
        xData: sheet["#{x_data.cells.first.reference}:#{x_data.cells.last.reference}"]
      )
    end

    p.serialize('big_scatter_full_range.xlsx')
  end

  x.report('adding series by first & last elements') do
    p = Axlsx::Package.new
    wb = p.workbook
    sheet = wb.add_worksheet
    chart = sheet.add_chart(Axlsx::ScatterChart)

    10.times do
      x_data = sheet.add_row(random_row.call)
      y_data = sheet.add_row(random_row.call)

      chart.add_series(
        yData: [y_data.cells.first, y_data.cells.last],
        xData: [x_data.cells.first, x_data.cells.last]
      )
    end

    p.serialize('big_scatter_first_and_last_elements.xlsx')
  end
end
```

Here are shocking results:
```
Rehearsal --------------------------------------------------------------------------
adding series by full range             23.369594   0.170882  23.540476 ( 23.729006)
adding series by first & last elements   2.229857   0.039330   2.269187 (  2.281591)
---------------------------------------------------------------- total: 25.809663sec

                                             user     system      total        real
adding series by full range             25.282062   0.201280  25.483342 ( 25.800421)
adding series by first & last elements   2.635578   0.037376   2.672954 (  2.679453)
```

Additionally, `big_scatter_full_range.xlsx` is two times larger than `big_scatter_first_and_last_elements.xlsx` (in my case it's `1,793,201 bytes` vs `921,666 bytes`.

**Comment by randym** [comment]
The performance benefits here could be great.

1. You might consider changing  the implementation of ```Axlsx.sort_cells``` to use ```sort_by(&pos)``` instead of removing the method to maintain backwards compatibility.

2. Unless I am reading this wrong these two examples create two very different series. The first only serializes two data points. The second serializes every data point in the collections of cells. That would definitely impact your file size, and I assume it would also impact the generated chart.

```
chart.add_series(
  yData: [y_data.cells.first, y_data.cells.last],
  xData: [x_data.cells.first, x_data.cells.last]
)
```
and
```
chart.add_series(
   yData: y_data.cells,
   xData: x_data.cells
)
```

https://github.com/caxlsx/caxlsx/blob/master/lib/axlsx/drawing/num_data.rb

Can you confirm that only adding the first and last data point for the series creates the same chart as adding all the data points you want to map?  If my assumptions are wrong that would be a huge win and could motivate fundamental changes in how data series are serialized.

**Comment by olegykz** [comment]
Ok, here is my snippet to test the charts (I've started to use columns for the chart data cause MacOS Numbers complains if we have a lot of columns):
```ruby
p = Axlsx::Package.new.tap { |p| p.use_shared_strings = true }
wb = p.workbook
sheet = wb.add_worksheet
chart = sheet.add_chart(Axlsx::ScatterChart)

(1..100).step(0.1).each do |point|
  sheet.add_row [point, Math.cos(point), point, Math.cos(point + 10)]
end

chart.add_series(
  yData: sheet["#{sheet.cols[1].first.reference}:#{sheet.cols[1].last.reference}"],
  xData: sheet["#{sheet.cols[0].first.reference}:#{sheet.cols[0].last.reference}"],
  title: 'Full range cos'
)

chart.add_series(
  yData: [sheet.cols[3].first, sheet.cols[3].last],
  xData: [sheet.cols[2].first, sheet.cols[2].last],
  title: 'First & last cell range'
)

p.serialize('test_chart.xlsx')
```

This is how the chart looks in Microsoft Excel (MacOS):
image

And this is Apple Numbers:
image

Some how Number thinks that corrupted line has only two values for X-axis (1 and 2, not sure how it choose them, as we have numbers in between)

**Comment by olegykz** [comment]
I've changed `xData` of `ScatterSeries` to use `NumDataSource` class instead of `AxDataSource`, and now the chart looks fine in Numbers:
image

**Comment by noniq** [comment]
Phew, there's quite a lot going on in this PR 😎  To summarize:

 1) Optimize `Axlsx.cell_range` by using `minmax_by` instead of sorting the cells. I think that’s a safe bet (the sorted cells are not used for anything else in this method).

 2)  A possible optimization for generating scatter charts by only using the first and last cell of the range instead of all cells. I’m a bit hesitant about this one: It seems to require changing the type of the data source to work correctly in Numbers (https://github.com/caxlsx/caxlsx/pull/82#issuecomment-785741604) – does this have any other impact? Is it 100% backward compatible? What about Libre Office etc.?

I suggest merging 1), but keeping this PR open so that 2) can be further explored and discussed. Thoughts?

**Comment by olegykz** [comment]
@noniq https://github.com/caxlsx/caxlsx/pull/94 here is point number 1 - safe part extraction.

Regarding point number 2 - I'll back with the results as soon as I get the chance to play with Libre Office

**Comment by straydogstudio** [comment]
Keeping open

**Comment by olegykz** [comment]
@straydogstudio I guess this one should be reopened, as it was closed automatically by GH actions

**Comment by olegykz** [comment]
> ...
> 
> Regarding point number 2 - I'll back with the results as soon as I get the chance to play with Libre Office

image
that's how it looks in Libre Office 
(v7.3, macOS)

**Comment by olegykz** [comment]
@straydogstudio so now the PR contains only the fix for the data source of X-axis for scatter series, which works good in Numbers, LibreOffice & MS Excel

**Pull request closed without merging**
