### PR TITLE
Update RuboCop dependency

### PR DESCRIPTION
**Pull request by tagliala**
### TODO
- [ ] Pin to exact versions
- [ ] Add a dependabot group

### Description
Updates RuboCop dependencies and pin them to exact versions to prevent CI failures with unrelated changes

### Your checklist for this pull request

- [ ] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [ ] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- [ ] If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [ ] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] I added an entry to the [changelog](../blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by kiskoza** [comment]
I've run into an issue with rubocop today: there were a PR without any code-style issues (#345), but rubocop failed on a new patch version of rubocop-minitest. I made a quick PR to fix the new offenses (#346), but I think we should handle this in a more conservative way, the CI shouldn't break as time goes by (except for Ruby Head, of course - we allow failures there).

My suggestion is to pin rubocop (and their plugins) to exact versions. Then we can do a regular / semi-regular updates when we want to bump up their version. What do you think?

**Comment by tagliala** [comment]
> My suggestion is to pin rubocop (and their plugins) to exact versions. Then we can do a regular / semi-regular updates when we want to bump up their version. What do you think?

I would pin to the exact version and then add a group to dependabot. A different approach would be to copy from rubocop all the configuration and explicitly enable cops, but that is not ideal too

I can take care of this change in this PR tomorrow

**Comment by kiskoza** [comment]
> I would pin to the exact version and then add a group to dependabot to upgrade all rubocop-related dependencies together. Then, if there is a new offense, we can fix it in that specific branch

This sounds good to me, thanks for working on this

**Comment by tagliala** [comment]
Failures depends by https://github.com/jnunemaker/crack/pull/79, thanks for taking care of that library

```
/home/runner/work/caxlsx/caxlsx/vendor/bundle/ruby/3.4.0+0/gems/crack-0.4.5/lib/crack/xml.rb:9: warning: bigdecimal was loaded from the standard library, but is not part of the default gems since Ruby 3.4.0. Add bigdecimal to your Gemfile or gemspec.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
```

**Pull request merged**
