### PR TITLE
Restructure examples folder

### PR DESCRIPTION
**Pull request by kiskoza**
This is my next idea to how to solve #46 : Bring the content of the wiki to the examples folder.

- [x] Unified code samples: Easy to check if new files has a short, informative code snippet
- [x] Descriptive examples: Easy to check if new files has description and image about the output
- [x] Discoverable examples: In `examples/README.md` we could sort the examples by categories, etc
- [x] Separate files: All examples will be in a separate file
- [x] Runnable examples: I added a `example_runner.rb`* that can extract the snippets from the markdown files and run all of them, or specific ones

&ast; I used this name because we already have an example.rb that I didn't want to delete right now, but we could reuse that name if we decide to migrate all examples to this format

### CODE REVIEW

**Comment by simi** [comment]
Looks amazing!

**Comment by noniq** [comment]
Absolutely amazing, thank you very much!

Should we merge this already, or do you want to add / restructure even more of the examples?

**Comment by kiskoza** [comment]
Let's wait for a few more days for more opinions. If there's no objection, I'll transform the rest of the examples too.

**Comment by noniq** [comment]
I can’t imagine any objections to these impressive improvements – but you’re right, let’s wait for a few days just to be sure. 😀

**Comment by kiskoza** [comment]
Good news everyone! I'm ready with this PR, the CI passed too, so next step should be to please take a look at it and find every line of code that should be fixed :smile:

**Comment by straydogstudio** [comment]
@noniq Any further thoughts on this?

**Comment by noniq** [comment]
I think this is a vast improvement for caxlx’s documentation, so thanks again @kiskoza for your amazing work!

I wonder if we should somehow integrate this into the test suite and/or ci checks? Like designating the current example documents as “known good” state, and having each test run regenerate and compare the documents to make sure there are no inadvertent changes?

**Pull request merged**
