### PR TITLE
Allow to set cell type to `date`

### PR DESCRIPTION
**Pull request by artplan1**
`date` type is valid cell type, but is missing in validator. It's impossible to set it explicitly.

Fixes https://github.com/caxlsx/caxlsx/issues/26

If this can be tested somehow, please let me know, not sure what test to add for this small change

### CODE REVIEW

**Comment by kiskoza** [comment]
I think you should [inclde the new value](https://github.com/caxlsx/caxlsx/blob/e4aeec68c8b7bb699db876df375a1e98187b21ac/test/util/tc_validators.rb#L130) in the `test/util/tc_validators.rb` file at least. Browsing those test cases might give you an idea of a new test too

**Comment by artplan1** [comment]
hey @kiskoza, thank you for feedback.
I've added value to `validate_data_validation_type` test + added value casting to date

**Comment by straydogstudio** [comment]
Thanks for the work @artplan1

**Comment by straydogstudio** [comment]
Released in 3.0.4

**Pull request merged**
