### PR TITLE
Revert formula characters other than =

### LINKED ISSUE #207: 3.4.0 breaks compatibility with 3.3.0 around formulas.
3.4.0 does not escape formulas by default, while 3.3.0 does (if escape_formulas is not set either way).
Therefore sheets with formulas are now attempting to evaluate them, or the formulas will get removed altogether if invalid.

### PR DESCRIPTION
**Pull request by johnnyshields**
Follow-up to #190 based on @noniq's comment. Fixes #207, #208.

Suggest to release as 3.4.1.

### CODE REVIEW

**Comment by johnnyshields** [comment]
@noniq

**Review by kiskoza — APPROVED** [review]

**Comment by noniq** [comment]
Thanks for the quick response! I think it does the right thing. I’ll look at it in detail later today.

**Comment by noniq** [comment]
(I especially want to think about the tests – do all current tests regarding this behaviour still make sense, do we need additional / different tests, …)

**Comment by johnnyshields** [comment]
@noniq re: tests, this reverts us back the to the 3.3.0 behavior, so I'd say let's go ahead and merge and release this as 3.4.1 to "stop the bleeding" for existing users, while we conduct further investigation here. Any change to the behavior (if needed) should be released as part of 4.0.0.

**Comment by noniq** [comment]
Merged. I also added some tests that would fail with the (now reverted) behaviour from 3.4.0, just to make sure we won’t run into this problem in the future again. Thank you!

Let’s release 3.4.1 asap.

**Pull request merged**
